select 
p.idprontuario, 
p.idcliente, 
p.iddependente, 
p.matricula, 
p.idendereco, 
p.paciente, 
p.idade, 
p.datanascimento,
p.peso, 
p.altura, 
p.parterialinicio, 
p.parterialfim, 
p.doencascronicas, 
p.medicaoanterior, 
p.queixa, 
p.conduta,
p.desativado, 
p.datainicioconsulta, 
p.datafimconsulta, 
p.idmedico, 
p.observacao, 
p.informacao, 
p.temperatura,
p.bpm, 
p.idespecialidade, 
p.especialidade, 
p.nomesocial, 
p.pacienteatendido,
m.Nome as profissional_atendente 
from cad_prontuario p
left join cad_medico m on m.idMedico = p.idmedico
where paciente = ? and p.DataNascimento = ?